# Generated by Django 3.2.4 on 2021-06-16 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_diarista_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarista',
            name='numero',
        ),
    ]
